# Generated by Django 3.1 on 2020-08-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200801_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msgId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=30),
        ),
    ]
